<a href="https://colab.research.google.com/github/hufsaim/T10402201/blob/master/ch03/linear_reg_concise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

http://d2l.ai/chapter_linear-networks/linear-regression-concise.html


In [ ]:
import numpy as np
import torch
from torch.utils import data

In [ ]:
def synthetic_data(w, b, num_examples):  #@save
    """Generate y = Xw + b + noise."""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

- model construction (pytorch nn module)

In [ ]:
# `nn` is an abbreviation for neural networks
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

print(net[0].weight.data)
print(net[0].bias.data)

tensor([[-0.0134,  0.0029]])
tensor([0.])


- hyperparameters

In [ ]:
num_epochs = 3
batch_size = 10
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

- load examples(synthetic)

In [ ]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

- data loader

In [ ]:
data_iter = data.DataLoader(data.TensorDataset(*(features, labels)), batch_size, shuffle=True)

In [ ]:
next(iter(data_iter))

[tensor([[ 0.6057,  0.5036],
         [-1.5446,  0.3142],
         [-3.0851,  0.4709],
         [-0.4336,  0.6667],
         [ 0.2393, -2.4849],
         [ 0.5690, -1.6878],
         [ 1.0622, -0.3432],
         [-1.2637, -1.0763],
         [-0.0656, -0.5170],
         [-0.4463, -0.4912]]), tensor([[ 3.7095],
         [ 0.0330],
         [-3.5553],
         [ 1.0695],
         [13.1459],
         [11.0708],
         [ 7.5048],
         [ 5.3339],
         [ 5.8243],
         [ 4.9803]])]

- train a model

In [ ]:
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000273
epoch 2, loss 0.000102
epoch 3, loss 0.000101


- check results

In [ ]:
w = net[0].weight.data
b = net[0].bias.data
print(w,b)

tensor([[ 2.0000, -3.4007]]) tensor([4.2011])
